databases:
  - name: GameXpense
    databaseName: gamexpense
    user: gamexpense_user

services:
  - type: web
    name: GameXpense
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gamexpense
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false